export const hiraganas = [
    'あ', 'い', 'う', 'え', 'お',
    'か', 'き', 'く', 'け', 'こ',
    'さ', 'し', 'す', 'せ', 'そ',
    'た', 'ち', 'つ', 'て', 'と',
    'な', 'に', 'ぬ', 'ね', 'の',
    'は', 'ひ', 'ふ', 'へ', 'ほ',
    'ま', 'み', 'む', 'め', 'も',
    'や', 'ゆ', 'よ',
    'ら', 'り', 'る', 'れ', 'ろ',
    'わ', 'を', 'ん', // <-- INDEX 45 (46ème position)
    'が', 'ぎ', 'ぐ', 'げ', 'ご',
    'ざ', 'じ', 'ず', 'ぜ', 'ぞ',
    'だ', 'ぢ', 'づ', 'で', 'ど',
    'ば', 'び', 'ぶ', 'べ', 'ぼ',
    'ぱ', 'ぴ', 'ぷ', 'ぺ', 'ぽ', // <-- INDEX 60 (61ème position)
    'きゃ', 'きゅ', 'きょ',
    'しゃ', 'しゅ', 'しょ',
    'ちゃ', 'ちゅ', 'ちょ',
    'にゃ', 'にゅ', 'にょ',
    'ひゃ', 'ひゅ', 'ひょ',
    'みゃ', 'みゅ', 'みょ',
    'りゃ', 'りゅ', 'りょ',
    'ぎゃ', 'ぎゅ', 'ぎょ',
    'じゃ', 'じゅ', 'じょ',
    'びゃ', 'びゅ', 'びょ',
    'ぴゃ', 'ぴゅ', 'ぴょ',
];

export const katakanas = [
    'ア', 'イ', 'ウ', 'エ', 'オ',
    'カ', 'キ', 'ク', 'ケ', 'コ',
    'サ', 'シ', 'ス', 'セ', 'ソ',
    'タ', 'チ', 'ツ', 'テ', 'ト',
    'ナ', 'ニ', 'ヌ', 'ネ', 'ノ',
    'ハ', 'ヒ', 'フ', 'ヘ', 'ホ',
    'マ', 'ミ', 'ム', 'メ', 'モ',
    'ヤ', 'ユ', 'ヨ',
    'ラ', 'リ', 'ル', 'レ', 'ロ',
    'ワ', 'ヲ', 'ン', 
    'ガ', 'ギ', 'グ', 'ゲ', 'ゴ',
    'ザ', 'ジ', 'ズ', 'ゼ', 'ゾ',
    'ダ', 'ヂ', 'ヅ', 'デ', 'ド',
    'バ', 'ビ', 'ブ', 'ベ', 'ボ',
    'パ', 'ピ', 'プ', 'ペ', 'ポ', 
    'キャ', 'キュ', 'キョ',
    'シャ', 'シュ', 'ショ',
    'チャ', 'チュ', 'チョ',
    'ニャ', 'ニュ', 'ニョ',
    'ヒャ', 'ヒュ', 'ヒョ',
    'ミャ', 'ミュ', 'ミョ',
    'リャ', 'リュ', 'リョ',
    'ギャ', 'ギュ', 'ギョ',
    'ジャ', 'ジュ', 'ジョ',
    'ビャ', 'ビュ', 'ビョ',
    'ピャ', 'ピュ', 'ピョ',
];

export const romajis = [
    'a', 'i', 'u', 'e', 'o',
    'ka', 'ki', 'ku', 'ke', 'ko',
    'sa', 'shi', 'su', 'se', 'so',
    'ta', 'chi', 'tsu', 'te', 'to',
    'na', 'ni', 'nu', 'ne', 'no',
    'ha', 'hi', 'fu', 'he', 'ho',
    'ma', 'mi', 'mu', 'me', 'mo',
    'ya', 'yu', 'yo',
    'ra', 'ri', 'ru', 're', 'ro',
    'wa', 'wo', 'n', 
    'ga', 'gi', 'gu', 'ge', 'go',
    'za', 'ji', 'zu', 'ze', 'zo',
    'da', 'ji', 'zu', 'de', 'do',
    'ba', 'bi', 'bu', 'be', 'bo',
    'pa', 'pi', 'pu', 'pe', 'po', 
    'kya', 'kyu', 'kyo',
    'sha', 'shu', 'sho',
    'cha', 'chu', 'cho',
    'nya', 'nyu', 'nyo',
    'hya', 'hyu', 'hyo',
    'mya', 'myu', 'myo',
    'rya', 'ryu', 'ryo',
    'gya', 'gyu', 'gyo',
    'ja', 'ju', 'jo',
    'bya', 'byu', 'byo',
    'pya', 'pyu', 'pyo',
];

export const kanaWords = [
    "ねこ",
    "いぬ",
    "あめ",
    "き",
    "あさ",
    "かさ",
    "いす",
    "ゆ",
    "はな",
    "とけい",
    "ね",
    "うま",
    "すし",
    "ひ",
    "りんご",
    "す",
    "よる",
    "かい",
    "くるま",
    "かわ",
    "いえ",
    "こうえん",
    "しんぶん",
    "ざっし",
    "てがみ",
    "かぎ",
    "まち",
    "うみ",
    "ひる",
    "ゆうがた",
    "ゆうべ",
    "あさって",
    "きのう",
    "きょう",
    "あした",
    "はる",
    "なつ",
    "あき",
    "ふゆ",
    "いち",
    "に",
    "さん",
    "し",
    "ご",
    "ろく",
    "しち",
    "はち",
    "きゅう",
    "じゅう",
    "おん",
    "たべもの",
    "のみもの",
    "ねむり",
    "ひるね",
    "きっさてん",
    "えき",
    "ほんや",
    "てんき",
    "ふた",
    "めがみ",
    "さかな",
    "こうちゃ",
    "くつ",
    "にく",
    "やさい",
    "くだもの",
    "かいぎ",
    "あたま",
    "あし",
    "て",
    "てくび",
    "は",
    "はね",
    "かお",
    "め",
    "くち",
    "ひげ",
    "あご",
    "せなか",
    "い",
    "うで",
    "こし",
    "みみ",
    "しっぽ"
];
export const romajiWords = [
    "neko",
    "inu",
    "ame",
    "ki",
    "asa",
    "kasa",
    "isu",
    "yu",
    "hana",
    "tokei",
    "ne",
    "uma",
    "sushi",
    "hi",
    "ringo",
    "su",
    "yoru",
    "kai",
    "kuruma",
    "kawa",
    "ie",
    "kouen",
    "shinbun",
    "zasshi",
    "tegami",
    "kagi",
    "machi",
    "umi",
    "hiru",
    "yuugata",
    "yuube",
    "asatte",
    "kinou",
    "kyou",
    "ashita",
    "haru",
    "natsu",
    "aki",
    "fuyu",
    "ichi",
    "ni",
    "san",
    "shi",
    "go",
    "roku",
    "shichi",
    "hachi",
    "kyuu",
    "juu",
    "on",
    "tabemono",
    "nomimono",
    "nemuri",
    "hirune",
    "kissaten",
    "eki",
    "honya",
    "tenki",
    "futa",
    "megami",
    "sakana",
    "koucha",
    "kutsu",
    "niku",
    "yasai",
    "kudamono",
    "kaigi",
    "atama",
    "ashi",
    "te",
    "tekubi",
    "ha",
    "hane",
    "kao",
    "me",
    "kuchi",
    "hige",
    "ago",
    "senaka",
    "i",
    "ude",
    "koshi",
    "mimi",
    "shippo"
];

export const translatedWords = [
    "chat",
    "chien",
    "pluie",
    "arbre",
    "matin",
    "parapluie",
    "chaise",
    "chaud",
    "fleur",
    "montre",
    "racine",
    "cheval",
    "sushi",
    "soleil",
    "pomme",
    "fumée",
    "soir",
    "mer",
    "voiture",
    "rivière",
    "maison",
    "parc",
    "journal",
    "magazine",
    "lettre",
    "clé",
    "ville",
    "océan",
    "midi",
    "après-midi",
    "hier",
    "demain",
    "printemps",
    "été",
    "automne",
    "hiver",
    "un",
    "deux",
    "trois",
    "quatre",
    "cinq",
    "six",
    "sept",
    "huit",
    "neuf",
    "dix",
    "son",
    "nourriture",
    "boisson",
    "sommeil",
    "sieste",
    "café",
    "gare",
    "librairie",
    "temps",
    "couvercle",
    "déesse",
    "poisson",
    "thé",
    "chaussure",
    "viande",
    "légume",
    "fruit",
    "réunion",
    "tête",
    "pied",
    "main",
    "poignet",
    "dent",
    "aile",
    "visage",
    "œil",
    "bouche",
    "barbe",
    "menton",
    "dos",
    "dent",
    "bras",
    "taille",
    "oreille",
    "queue"
];
